spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/suraksha_db
spring.datasource.username=postgres
spring.datasource.password=Otaku@2006

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true